### ISSUE TITLE
Ensemble abundance raster (MML - harbor seal team)

### ISSUE THREAD

**Issue by MargaretSiple-NOAA** [alaska-groundfish-efh/product-requests#1]
**Requesters**: Brett McClintock, Shawn Dahle, Stacie Hardie, and Josh London

**Data product**: Ensemble-predicted abundances (as .gri files) for the following species: 

- Arrowtooth flounder (Atheresthes stomias)
- Northern rock sole (Lepidopsetta polyxystra)
- Pacific cod (Gadus macrocephalus)
- Southern rock sole (Lepidopsetta bilineata)
- Pacific ocean perch (Sebastes alutus)
- Atka mackerel (Pleurogrammus monopterygius)
- Northern rockfish (Sebastes polyspinis)
- Walleye pollock (Gadus chalcogrammus)
- Flathead sole (Hippoglossoides elassodon)
- Yellow Irish lord (Hemilepidotus jordani)
- Golden king crab (Lithodes aequispinus)
- Kamchatka flounder (Atheresthes evermanni)
- Shortspine thornyhead (Sebastolobus alascanus)
- Shortraker rockfish (Sebastes borealis)
- Blackspotted rockfish (Sebastes melanostictus)
- Pacific giant octopus sp. (Enteroctopus dofleini)
- Sablefish (Anoplopoma fimbria)
- Rougheye rockfish (Sebastes aleutianus)
- Alaska skate (Bathyraja parmifera)
- Greenland turbot (Reinhardtius hippoglossoides)
- Dusky rockfish (Sebastes variabilis)
- Dover sole (Microstomus pacificus)
- Aleutian skate (Bathyraja aleutica)
- Great sculpin (Myoxocephalus polyacanthocephalus)
- Rex sole (Glyptocephalus zachirus)
- Bigmouth sculpin (Hemitripterus bolini)
- Harlequin rockfish (Sebastes variegatus)

**Comment by jmlondon** [comment]
adding GH accounts to this issue

- @bmcclintock
- @staciekozhardy
- @jmlondon

**Comment by MargaretSiple-NOAA** [comment]
Hi @bmcclintock , @StacieKozHardy and @jmlondon -- did you all find the rasters you needed in the google drive folder that Ned sent along? If so I will close this issue. Thanks!

**Comment by MargaretSiple-NOAA** [comment]
Hi all-- any updates on this? Did you get what you need?

**Comment by MargaretSiple-NOAA** [comment]
Hi @jmlondon @bmcclintock @StacieKozHardy et al -- sorry for the additional request on this request (ha!) but if you could add the info here about what you want to use the data products for, I would be much obliged. Jodi just asked us to add it to each of the requests so we can keep track of where the EFH products are used in other NOAA products. I will add it to the template for future requests.

Here's what I have in my email: 

> [This product will be used to determine] which potential prey species (or groups) to include in our harbor seal foraging analysis. This may largely depend on the spatial variability in the ensemble-predicted abundances

Would you like to add anything to that?

Thanks!

**Comment by MargaretSiple-NOAA** [comment]
Hi all - I am cleaning up these data requests and it looks like this one has been resolved. If you still need help, please re-open it.
