### ISSUE TITLE
GOA Atlantis modeling group

### ISSUE THREAD

**Issue by MargaretSiple-NOAA** [alaska-groundfish-efh/product-requests#2]
**Requesters**: GOA Atlantis group; Alberto Rovellini, Martin Dorn, Jodi Pirtle, Isaac Kaplan

**Products**: 

- [x] Ensemble-predicted abundance rasters for GOA and the AI (to fill in western regions)
- [x] Draft SDM methods for GOA

**Comment by MargaretSiple-NOAA** [comment]
Rasters shared with Albi on 12/15/21. Draft methods sent 1/12/22. Note to send more detailed methods (with equations) to all product requesters in the future (#3 )

**Comment by jeremyharris7** [comment]
Updated the rasters shared with Albi on 3/22/22.
