### ISSUE TITLE
Snow crab EFH shapefile

### ISSUE THREAD

**Issue by MargaretSiple-NOAA** [alaska-groundfish-efh/product-requests#4]
Requesting scientist: Erin Fedewa @Erin-Fedewa-NOAA

Species: Snow crab

They may use EFH map products as spatial boundaries for indicators in the Ecosystem and Socioeconomic Profiles for groundfish and crab. Requesting a shapefile with EFH boundaries for snow crab.

**Comment by MargaretSiple-NOAA** [comment]
Hi @Erin-Fedewa-NOAA -- see if the folder [here ](https://drive.google.com/drive/folders/12UzivGyWz_gRQ1ylASTFojHT6DyJao23?usp=sharing)is the shapefile you need. Demo of what it looks like (from ArcGIS) below.
![snowcrabdemo](https://user-images.githubusercontent.com/73858992/163429236-e0e21a7e-0ac9-48b0-ac6d-5e38447d85e2.png)

**Comment by Erin-Fedewa-NOAA** [comment]
Perfect, thank you so much!!
