### ISSUE TITLE
RE and BS rockfish EFH area raster + species-specific maps

### ISSUE THREAD

**Issue by MargaretSiple-NOAA** [alaska-groundfish-efh/product-requests#5]
**Requester**: Jane Sullivan ( @JaneSullivan-NOAA )
**Project**: Accounting for differences between RE and BS rockfish in stock assessment

**Products Requested**: 

- [x] Species-specific EFH maps for RE and BS (caveat: these are not easy to distinguish in the field so maps should be used with a _great_ deal of caution and with this caveat in mind.)
- [x] EFH core habitat shapefiles for the complex (the second request is in response to a SSC/PT recommendation)

**What will this product be used for?**:
### Otolith morphometry
(from Jane): "using the otolith morphology species discrimination model from Jeremy Harris' [paper](https://spo.nmfs.noaa.gov/sites/default/files/pdf-content/fish-bull/harris_0.pdf) to validate species-specific maturity curves from Christina's [paper](https://www.tandfonline.com/doi/abs/10.1080/00028487.2017.1285352), which relied on field identification"

**Comment by MargaretSiple-NOAA** [comment]
@JaneSullivan-NOAA -- sorry I am just getting to a short back-log of product requests. This is just for GOA, right?

**Comment by JaneSullivan-NOAA** [comment]
Yes! Just GOA. No rush, we could even table it until after field season and stock assessments are over.

**Comment by MargaretSiple-NOAA** [comment]
Hi Jane-- take a look at the files [here ](https://drive.google.com/drive/folders/1RYG1HM87iJEwnM0DWYZG17mEFweS0E77?usp=sharing)and see if these are what you need. I made the core EFH shapefiles for the complex myself with some instruction from Jeremy; if they contained two different colors those colors represent core EFH (layer = 4) and hotpots (layer = 5). If this is what you're looking for, feel free to close this issue! 

Code used to produce shapefiles for core area is [here](https://github.com/alaska-groundfish-efh/product-requests/blob/main/fulfillment-code/5_rougheyeblackspotted.R).

**Comment by JaneSullivan-NOAA** [comment]
I didn't realize this was pending my approval. I whole-heartedly approve! Thank you for your help.

**Comment by MargaretSiple-NOAA** [comment]
Great! I will close. To be quite honest I forgot that this was the status too!
