### ISSUE TITLE
YFS, pollock, PCOD EFH shapefiles for GOA and Bering Sea

### ISSUE THREAD

**Issue by MargaretSiple-NOAA** [alaska-groundfish-efh/product-requests#6]
**Data product requested (EFH, abundance, etc.)**:  EFH shapefiles, Methods section of in-review tech memo

**Species**: Yellowfin sole, pollock, Pacific cod

**Lifestage(s)**: Early juvenile, subadult, adult

**Region(s)** (GOA, AI, Bering Sea): GOA and Bering Sea

**Format**: 

- [ ] Raster
- [X] Shapefile

**Research team making the request** (PI /requester name, and tag team members with GitHub accounts, or email address if requestor does not have a GitHub account. Division is nice too.): Beth Matta (@BethMatta-NOAA) and Esther Goldstein (@esther2go)

**What will this EFH product be used for?**: A publication about spatial variation in body condition.

**Comment by MargaretSiple-NOAA** [comment]
Shapefiles for each of these stock/life stage/region combos are deposited [here](https://drive.google.com/drive/folders/1nZTPPLaNGxcxJhGsNK78TOXYW3dQe1iJ?usp=sharing). Beth and Esther, please check that these are what you need and close this issue if your request has been fulfilled!

**Comment by BethMatta-NOAA** [comment]
Thanks, @MargaretSiple-NOAA, the files are just what we need! It doesn't look like we're assigned to this issue, so I'm not sure how to close it.

**Comment by MargaretSiple-NOAA** [comment]
Aha! Well, that's ok. I will close. Glad you got what you needed :)
